typography_spectrum: 0.99116
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7922227981034666
  lightness: 0.7622638689354062
  saturation: 0.6360691823065281
  rhythmicContrast: 0.4187858847435564
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05307137966156006
analytics:
  google: null
  facebook: null
  twitter: null
name: dwimmer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Tie One On
purpose: []
